export default [
    {
        name:'老师信息管理',
        childrenShow:'hide',
        children:[
            {
                name:'入库老师',
                toLink:'/'
            },
            {
                name:'回收站老师',
                toLink:'/test'
            }
        ]
    },
    {
        name:'老师信息管理2',
        childrenShow:'hide',
        children:[
            {
                name:'入库老师2',
                childrenShow:'hide',
                children:[
                    {
                        name:'入库老师21入库老师21入库老师21入库老师21入库老师21入库老师21',
                        toLink:'xxx'
                    },
                    {
                        name:'入库老师21入库老师21入库老师21入库老师21132132132321',
                        toLink:'xxx'
                    }
                ]
            },
            {
                name:'回收站老师2',
                toLink:'xxx'
            }
        ]
    }
];